## 行列演算の基礎

-ベクトルの定義
-行列の定義
-転置
-逆行列
-行列積

In [1]:
import numpy as np

In [4]:
# ベクトルの定義
x= np.array([[1],[2],[3]])
print(x)

[[1]
 [2]
 [3]]


In [6]:
# 行列の定義
X=np.array([[1,2],[3,4]])
print(X)

[[1 2]
 [3 4]]


In [8]:
#転置
Xt = X.T
print(Xt)

[[1 3]
 [2 4]]


In [11]:
# 逆行列
# linear algebra:線形代数
X_inv = np.linalg.inv(X)
print(X_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [12]:
# 行列積
XX_inv = np.dot(X,X_inv)
print(XX_inv)

[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


# よくある間違い


In [13]:
# ベクトルを一次配列で表現
x=np.array([1,2,3])
x

array([1, 2, 3])

In [14]:
# 転置できない
x.T

array([1, 2, 3])

In [15]:
# ベクトルを二次元配列で表現
x=np.array([[1,2,3]])
x

array([[1, 2, 3]])

In [17]:
# 転置できる
x.T

array([[1],
       [2],
       [3]])

## Numpyでよく使う処理

In [ ]:
X=np.array([
    [2, 3, 4],
    []
])

In [18]:
row,col= X.shape

In [19]:
row
col

2

In [20]:
row

2

In [21]:
col

2